import Nav from './components/nav';
import './globals.css';
import { Bebas_Neue, Oswald } from 'next/font/google';

// Configure Boldone (for h1)
const bebas = Bebas_Neue({
	subsets: ['latin'],
	weight: '400', // Bold weight
	variable: '--font-bebas',
});

// Configure Oswald (for other text)
const oswald = Oswald({
	subsets: ['latin'],
	weight: ['400', '500', '600'], // Multiple weights
	variable: '--font-oswald',
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${bebas.variable} ${oswald.variable}`}>
				<Nav />
				{children}
			</body>
		</html>
	);
}
